# Configuración del build (compilación)
[build]
builder = "DOCKERFILE"

# Configuración del despliegue GENERAL
[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
# --- ¡LA MAGIA ESTÁ AQUÍ! ---
releaseCommand = "bundle exec rails db:migrate && bundle exec rails ip_lookup:setup"

# --- Definición explícita de los servicios ---

# 1. Servicio WEB: Su ÚNICA misión es correr el servidor.
[[deploy.services]]
name = "web"
healthcheckPath = "/health"
healthcheckTimeout = 120
healthcheckInterval = 15
# El comando de arranque ahora es simple y directo
startCommand = "bundle exec puma -C config/puma.rb -b 0.0.0.0 -p ${PORT}"

# 2. Servicio WORKER: Su ÚNICA misión es correr Sidekiq.
[[deploy.services]]
name = "worker"
startCommand = "bundle exec sidekiq -C config/sidekiq.yml"

# Variables de Entorno - AÑADE TU CLAVE AQUÍ
[env]
RAILS_ENV = "production"
RACK_ENV = "production"
RAILS_LOG_TO_STDOUT = "true"
RAILS_SERVE_STATIC_FILES = "true"
RAILS_MAX_THREADS = "5"
BUNDLE_WITHOUT = "development:test"
BUNDLE_DEPLOYMENT = "true"
FORCE_SSL = "true"
ENABLE_ACCOUNT_SIGNUP = "true"
ACTIVE_STORAGE_SERVICE = "local"
MAILER_SENDER_EMAIL = "noreply@tudominio.com"